/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 93
#define YY_END_OF_BUFFER 94
static yyconst short int yy_accept[203] =
    {   0,
        0,    0,    0,    0,   87,   87,   94,   93,   56,   46,
       54,   76,   77,   44,   42,   82,   43,   72,   45,   84,
       83,   50,   47,   51,   91,   91,   78,   79,   57,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   80,   55,   81,   87,   88,   49,   66,
       60,   67,   64,   62,   63,   75,   73,   86,   90,   65,
       85,   58,   52,   48,   53,   59,   92,   91,   91,   91,
       69,    1,   91,   91,   91,   91,   91,   91,   91,   91,
       91,   91,   10,   91,   91,   91,   12,   91,   14,   91,
       91,   91,   91,   91,   91,   91,   91,   91,   91,   91,

       91,   91,   91,   91,   68,   61,   87,   88,   88,   89,
       74,   90,   70,   71,   91,   91,   91,   91,   91,   91,
       91,   91,   91,   39,   40,   91,   11,   37,   38,   91,
       15,   91,   91,   18,   91,   20,   21,   22,   91,   91,
       91,   91,   91,   91,   91,   91,   91,   33,   91,   91,
       25,   91,   36,   91,   91,   91,   91,    6,    7,   91,
       91,   13,   16,   91,   19,   91,   24,   91,   91,   91,
       91,   30,   31,   91,   91,   91,   91,    2,    3,   91,
        5,   91,    9,   17,   91,   91,   91,   28,   29,   91,
       34,   35,   41,   91,    8,   23,   26,   27,   32,   91,

        4,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    1,    1,    4,    5,    1,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   14,   15,
       16,   17,   14,   18,   14,   14,   14,   19,   20,   21,
       22,   23,    1,    1,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   25,   24,   24,   24,   24,   24,   24,   24,
       26,    1,   27,   28,   24,    1,   29,   30,   31,   32,

       33,   34,   35,   36,   37,   24,   38,   39,   40,   41,
       42,   43,   24,   44,   45,   46,   47,   48,   49,   50,
       51,   24,   52,   53,   54,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[55] =
    {   0,
        1,    2,    3,    1,    1,    1,    1,    4,    1,    1,
        1,    1,    1,    3,    3,    3,    3,    3,    1,    1,
        1,    1,    1,    3,    3,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1
    } ;

static yyconst short int yy_base[209] =
    {   0,
        0,    0,    0,    0,  358,  357,  364,  367,  341,  340,
       50,  367,  367,  339,  338,  367,   34,  347,   51,  339,
      367,   39,  335,   40,  353,   55,  367,  367,  333,   62,
       64,   67,   63,   74,   78,   72,   81,   73,   65,   84,
       82,   80,   86,  367,   47,  367,    0,   66,  367,  367,
      367,  367,  367,  367,  367,  367,  332,  367,    0,  367,
      367,  331,  367,  367,  367,  330,  367,  348,   88,   90,
      367,  347,   94,   96,   83,  129,   92,  132,  135,  136,
      137,  138,  346,  139,  140,  142,  345,  141,  342,  143,
      144,  145,  146,  147,  150,  153,  149,  161,  154,  163,

      157,  158,  162,  165,  367,  367,    0,  314,  154,  367,
      367,    0,  367,  367,  167,  169,  168,  179,  166,  170,
      171,  173,  182,  323,  322,  172,  321,  320,  319,  193,
      318,  206,  211,  317,  215,  316,  314,  313,  216,  217,
      218,  219,  220,  221,  222,  223,  225,  312,  224,  226,
      311,  228,  310,  232,  227,  230,  238,  308,  307,  231,
      241,  306,  305,  236,  304,  233,  303,  242,  247,  237,
      234,  302,  301,  249,  243,  254,  256,  300,  299,  244,
      298,  257,  297,  294,  258,  259,  240,  293,  292,  279,
      291,  290,  289,  281,  286,  235,  160,   79,   77,  285,

       75,  367,  328,  332,   68,  336,  339,  343
    } ;

static yyconst short int yy_def[209] =
    {   0,
      202,    1,  203,  203,  204,  204,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  205,  205,  202,  202,  202,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  202,  202,  202,  206,  207,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  208,  202,
      202,  202,  202,  202,  202,  202,  202,  205,  205,  205,
      202,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  202,  202,  206,  207,  207,  202,
      202,  208,  202,  202,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

      205,    0,  202,  202,  202,  202,  202,  202
    } ;

static yyconst short int yy_nxt[422] =
    {   0,
        8,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   18,   19,    8,    8,    8,    8,    8,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       32,   25,   33,   34,   25,   25,   35,   25,   36,   37,
       25,   25,   38,   39,   40,   41,   42,   25,   43,   25,
       25,   44,   45,   46,   51,   55,   56,   67,   58,   62,
       63,   65,   66,   59,   67,   67,   67,   67,  105,   67,
       68,   52,   60,  109,   67,   67,   67,   67,  110,   67,
       67,   67,   67,   67,   67,   67,   67,   69,   67,   80,
       67,   81,   67,   85,   67,   86,   67,   96,   67,  106,

       70,   77,   82,   78,   90,   73,   72,   74,   75,   92,
       76,   87,   79,   91,   83,   84,   97,   88,   89,   95,
      102,  104,   93,  119,  103,  100,  115,   94,  118,   98,
       99,   67,  101,  116,   67,  117,  121,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
      124,   67,   67,  125,  128,   67,   67,  120,  129,   67,
       67,  109,   67,   67,   67,   67,  110,   67,   67,   67,
       67,   67,   67,   67,   67,   67,  126,  134,  122,  137,
      123,   67,  127,  130,   67,  132,  138,  140,  131,  141,
      133,  144,  136,  135,  148,   67,  143,  149,  139,  146,

      151,  150,  147,  158,  142,  152,  153,  154,   67,  145,
      155,  156,  159,   67,  160,  157,  161,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,  162,   67,   67,   67,   67,   67,   67,   67,   67,
       67,  164,   67,   67,   67,   67,   67,  165,  163,   67,
      167,   67,  170,  174,  172,  173,   67,  171,   67,   67,
       67,   67,  166,  168,  176,  169,  180,  175,  177,  178,
      181,  184,  179,  183,  182,  191,  185,  187,  186,  189,
      188,   67,  190,   67,  194,  198,  192,   67,   67,  197,
      193,   67,   67,   67,   67,   67,   67,  195,  196,   67,

       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,  199,   67,   67,   67,   67,   67,  201,   67,   67,
       67,   67,   67,   67,   67,   67,  202,  200,    8,    8,
        8,    8,   47,   47,   47,   47,  107,  107,  107,  108,
      108,  108,  108,  112,   67,  112,  112,   67,   67,   67,
       67,  114,  113,  111,   71,   67,   64,   61,   57,   54,
       53,   50,   49,  202,   48,   48,    7,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202
    } ;

static yyconst short int yy_chk[422] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   11,   17,   17,   26,   19,   22,
       22,   24,   24,   19,   30,   33,   31,   39,   45,   32,
      205,   11,   19,   48,   36,   38,   34,  201,   48,  199,
       35,  198,   42,   37,   41,   75,   40,   26,   43,   34,
       69,   34,   70,   35,   77,   35,   73,   39,   74,   45,

       26,   33,   34,   33,   36,   31,   30,   31,   32,   37,
       32,   35,   33,   36,   34,   34,   40,   35,   35,   38,
       42,   43,   37,   75,   42,   41,   69,   37,   74,   40,
       40,   76,   41,   70,   78,   73,   77,   79,   80,   81,
       82,   84,   85,   88,   86,   90,   91,   92,   93,   94,
       80,   97,   95,   81,   85,   96,   99,   76,   86,  101,
      102,  109,  197,   98,  103,  100,  109,  104,  119,  115,
      117,  116,  120,  121,  126,  122,   82,   93,   78,   95,
       79,  118,   84,   88,  123,   91,   96,   97,   90,   98,
       92,  100,   94,   93,  103,  130,   99,  104,   96,  101,

      115,  104,  102,  121,   98,  116,  117,  118,  132,  100,
      119,  119,  122,  133,  123,  120,  126,  135,  139,  140,
      141,  142,  143,  144,  145,  146,  149,  147,  150,  155,
      152,  130,  156,  160,  154,  166,  171,  196,  164,  170,
      157,  133,  187,  161,  168,  175,  180,  135,  132,  169,
      140,  174,  143,  147,  145,  146,  176,  144,  177,  182,
      185,  186,  139,  141,  150,  142,  156,  149,  152,  154,
      157,  164,  155,  161,  160,  175,  166,  169,  168,  171,
      170,  190,  174,  194,  180,  187,  176,  200,  195,  186,
      177,  193,  192,  191,  189,  188,  184,  182,  185,  183,

      181,  179,  178,  173,  172,  167,  165,  163,  162,  159,
      158,  190,  153,  151,  148,  138,  137,  200,  136,  134,
      131,  129,  128,  127,  125,  124,  108,  194,  203,  203,
      203,  203,  204,  204,  204,  204,  206,  206,  206,  207,
      207,  207,  207,  208,   89,  208,  208,   87,   83,   72,
       68,   66,   62,   57,   29,   25,   23,   20,   18,   15,
       14,   10,    9,    7,    6,    5,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,

      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202,  202,  202,  202,  202,  202,  202,  202,  202,  202,
      202
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "compiler/lex.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define STRING 1

#define ML_COMMENT 2

#line 10 "compiler/lex.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    char str[1024];
#line 538 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 17 "compiler/lex.l"


#line 688 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 203 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 367 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 19 "compiler/lex.l"
{ printf("Found KW_AS: %s\n", yytext); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 20 "compiler/lex.l"
{ printf("Found KW_BREAK: %s\n", yytext); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 21 "compiler/lex.l"
{ printf("Found KW_CONST: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 22 "compiler/lex.l"
{ printf("Found KW_CONTINUE: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 23 "compiler/lex.l"
{ printf("Found KW_CRATE: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 24 "compiler/lex.l"
{ printf("Found KW_ELSE: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 25 "compiler/lex.l"
{ printf("Found KW_ENUM: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 26 "compiler/lex.l"
{ printf("Found KW_EXTERN: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 27 "compiler/lex.l"
{ printf("Found KW_FALSE: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 28 "compiler/lex.l"
{ printf("Found KW_FN: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 29 "compiler/lex.l"
{ printf("Found KW_FOR: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 30 "compiler/lex.l"
{ printf("Found KW_IF: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 31 "compiler/lex.l"
{ printf("Found KW_IMPL: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 32 "compiler/lex.l"
{ printf("Found KW_IN: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 33 "compiler/lex.l"
{ printf("Found KW_LET: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 34 "compiler/lex.l"
{ printf("Found KW_LOOP: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 35 "compiler/lex.l"
{ printf("Found KW_MATCH: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 36 "compiler/lex.l"
{ printf("Found KW_MOD: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 37 "compiler/lex.l"
{ printf("Found KW_MOVE: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 38 "compiler/lex.l"
{ printf("Found KW_MUT: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 39 "compiler/lex.l"
{ printf("Found KW_PUB: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 40 "compiler/lex.l"
{ printf("Found KW_REF: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 41 "compiler/lex.l"
{ printf("Found KW_RETURN: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 42 "compiler/lex.l"
{ printf("Found KW_SELFVALUE: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 43 "compiler/lex.l"
{ printf("Found KW_SELFTYPE: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 44 "compiler/lex.l"
{ printf("Found KW_STATIC: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 45 "compiler/lex.l"
{ printf("Found KW_STRUCT: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 46 "compiler/lex.l"
{ printf("Found KW_SUPER: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 47 "compiler/lex.l"
{ printf("Found KW_TRAIT: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 48 "compiler/lex.l"
{ printf("Found KW_TRUE: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 49 "compiler/lex.l"
{ printf("Found KW_TYPE: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 50 "compiler/lex.l"
{ printf("Found KW_UNSAFE: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 51 "compiler/lex.l"
{ printf("Found KW_USE: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 52 "compiler/lex.l"
{ printf("Found KW_WHERE: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 53 "compiler/lex.l"
{ printf("Found KW_WHILE: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 56 "compiler/lex.l"
{ printf("Found TYPE_BOOL: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 57 "compiler/lex.l"
{ printf("Found TYPE_I32: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 58 "compiler/lex.l"
{ printf("Found TYPE_I64: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 59 "compiler/lex.l"
{ printf("Found TYPE_F32: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 60 "compiler/lex.l"
{ printf("Found TYPE_F64: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 61 "compiler/lex.l"
{ printf("Found TYPE_STRING: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 64 "compiler/lex.l"
{ printf("Found OPERATOR_PLUS: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 65 "compiler/lex.l"
{ printf("Found OPERATOR_MINUS: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 66 "compiler/lex.l"
{ printf("Found OPERATOR_MUL: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 67 "compiler/lex.l"
{ printf("Found OPERATOR_DIV: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 68 "compiler/lex.l"
{ printf("Found OPERATOR_MOD: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 70 "compiler/lex.l"
{ printf("Found OPERATOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 71 "compiler/lex.l"
{ printf("Found OPERATOR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 72 "compiler/lex.l"
{ printf("Found OPERATOR_NOT_EQUAL: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 73 "compiler/lex.l"
{ printf("Found OPERATOR_LESS: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 74 "compiler/lex.l"
{ printf("Found OPERATOR_MORE: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 75 "compiler/lex.l"
{ printf("Found OPERATOR_LESS_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 76 "compiler/lex.l"
{ printf("Found OPERATOR_MORE_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 78 "compiler/lex.l"
{ printf("Found OPERATOR_AMPERSAND: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 79 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_OR: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 80 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_NOT: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 81 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_XOR: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 82 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 83 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "compiler/lex.l"
{ printf("Found OPERATOR_AND: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "compiler/lex.l"
{ printf("Found OPERATOR_OR: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 88 "compiler/lex.l"
{ printf("Found OPERATOR_PLUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 89 "compiler/lex.l"
{ printf("Found OPERATOR_MINUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 90 "compiler/lex.l"
{ printf("Found OPERATOR_MUL_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 91 "compiler/lex.l"
{ printf("Found OPERATOR_DIV_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 92 "compiler/lex.l"
{ printf("Found OPERATOR_MOD_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 93 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_AND_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 94 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_OR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 95 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_XOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 96 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 97 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 99 "compiler/lex.l"
{ printf("Found OPERATOR_POINT: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 100 "compiler/lex.l"
{ printf("Found OPERATOR_RANGE: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 101 "compiler/lex.l"
{ printf("Found OPERATOR_RANGE_ASSIGMENT: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "compiler/lex.l"
{ printf("Found OPERATOR_ARROW: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 104 "compiler/lex.l"
{ printf("Found LEFT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 105 "compiler/lex.l"
{ printf("Found RIGHT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "compiler/lex.l"
{ printf("Found LEFT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 107 "compiler/lex.l"
{ printf("Found RIGHT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 108 "compiler/lex.l"
{ printf("Found LEFT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 109 "compiler/lex.l"
{ printf("Found RIGHT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 111 "compiler/lex.l"
{ printf("Found COMMA: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 112 "compiler/lex.l"
{ printf("Found SEMICOLON: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 113 "compiler/lex.l"
{ printf("Found COLON: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 114 "compiler/lex.l"
{ printf("Found TWO_COLON: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 117 "compiler/lex.l"
{ strcpy(str,""); BEGIN(ML_COMMENT); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 118 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 119 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 120 "compiler/lex.l"
{ printf("Found ML_COMMENT: %s\n", str);  BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 121 "compiler/lex.l"
{ printf("ML_COMMENT Error: comments are not closed"); BEGIN(INITIAL);}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 123 "compiler/lex.l"
{ printf("Found COMMENT: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 125 "compiler/lex.l"
{ printf("Found IDENTIFIER: %s\n", yytext);}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 126 "compiler/lex.l"
{ printf("Found MACROS: %s\n", yytext);}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 128 "compiler/lex.l"
ECHO;
	YY_BREAK
#line 1240 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 203 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 203 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 202);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 128 "compiler/lex.l"


