/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 140
#define YY_END_OF_BUFFER 141
static yyconst short int yy_accept[356] =
    {   0,
        0,    0,    0,    0,    0,    0,   93,   93,    0,    0,
      141,  139,    2,    1,   62,   98,   52,   60,  115,   82,
       83,   50,   48,   88,   49,   78,   51,  129,  129,   90,
       89,   56,   53,   57,  136,  136,   84,   85,   63,  136,
      136,  136,  136,  136,  136,  136,  136,  136,  136,  136,
      136,  136,  136,   86,   61,   87,  116,  126,  127,   99,
      100,  109,  110,   93,   94,   95,  112,  113,  114,   55,
       72,   66,   73,    0,    0,   70,   68,   69,   81,   79,
      133,   92,   97,   71,    0,  134,  129,  138,  138,  129,
      138,  138,  138,  138,  138,   91,   64,   58,   54,   59,

       65,  137,  136,  136,  136,   75,    3,  136,  136,  136,
      136,  136,  136,  136,  136,  136,  136,  136,   12,  136,
      136,  136,   14,  136,   16,  136,  136,  136,  136,  136,
      136,  111,    0,  136,  136,  136,  136,  136,  136,  136,
      136,  136,   74,   67,  116,  123,  122,  120,  121,  117,
      118,  119,    0,    0,   99,  106,  104,  105,  101,  102,
      103,    0,    0,   93,   95,   95,   96,  112,  114,    0,
        0,   80,  133,    0,    0,   97,    0,    0,  134,    0,
      138,    0,  135,  129,  138,  138,  138,  130,  138,  138,
      131,  132,   76,   77,  136,  136,  136,  136,  136,  136,

      136,  136,  136,  136,   44,   45,  136,   13,   42,   43,
      136,   17,  136,  136,   20,  136,   22,   23,   24,  136,
      136,  136,  136,  136,  136,  136,  136,  136,   35,  136,
      136,    0,    0,    0,    0,   38,    0,    0,  133,    0,
        0,  128,  128,  134,    0,    0,  135,  135,  138,  135,
      129,  138,  138,   27,  136,   41,  136,   47,  136,  136,
      136,    8,    9,  136,  136,   15,   18,  136,   21,  136,
       26,  136,  136,  136,  136,   32,   33,  136,  136,  136,
        0,  125,    0,  108,    0,   39,  133,  133,  128,    0,
        0,    0,    0,  134,  134,  135,    0,  138,  138,  138,

      136,    4,    5,  136,    7,  136,   11,   19,  136,  136,
      136,   30,   31,  136,   36,   37,    0,    0,    0,    0,
        0,  128,  128,  128,  134,    0,  130,  131,  132,   46,
      136,   10,   25,   28,   29,   34,    0,    0,    0,    0,
        0,  135,  136,    0,    0,    0,    0,    0,    6,    0,
      124,    0,  107,   40,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       21,   22,   23,   24,   23,   25,   25,   26,   27,   28,
       29,   30,    1,    1,   31,   31,   31,   31,   32,   31,
       33,   33,   33,   33,   33,   33,   33,   33,   33,   33,
       33,   33,   34,   33,   33,   33,   33,   33,   33,   33,
       35,   36,   37,   38,   39,    1,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   33,   49,   50,   51,   52,
       53,   54,   33,   55,   56,   57,   58,   59,   60,   61,
       62,   33,   63,   64,   65,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[66] =
    {   0,
        1,    2,    3,    4,    5,    1,    1,    1,    6,    1,
        1,    7,    8,    1,    8,    9,    1,   10,   10,   10,
       10,   10,   10,   10,   10,    1,    1,    1,    1,    1,
       11,   12,   13,   13,    1,   14,    1,    1,   15,   11,
       16,   11,   11,   12,   17,   13,   13,   13,   13,   13,
       13,   13,   18,   13,   13,   13,   13,   13,   13,   13,
       18,   13,    1,    1,    1
    } ;

static yyconst short int yy_base[389] =
    {   0,
        0,    0,   57,   58,   65,   66,   69,   70,   71,   72,
      968,  997,  997,  997,  934,  997,  932,   70,  997,  997,
      997,  931,  930,  997,   50,   67,   83,  125,   43,  932,
      997,   69,  924,   76,  948,  147,  997,  997,  916,   99,
      107,  148,  138,  185,  189,  110,  190,  103,  192,  188,
      196,  198,  106,  997,  178,  997,    0,  997,  211,    0,
      997,  997,  221,    0,  997,   96,    0,  997,  938,  997,
      997,  997,  997,  879,  892,  997,  997,  997,  997,  902,
       85,  997,    0,  997,  116,   93,  170,    0,  270,  294,
       97,  905,  907,  281,  325,  997,  898,  997,  997,  997,

      897,  997,  919,  210,  201,  997,  916,  208,  211,  204,
      213,  224,  214,  217,  220,  119,  118,  231,  915,  229,
      267,  245,  914,  255,  913,  223,  258,  249,  282,  270,
      294,  997,  119,  317,  303,  318,  324,  319,  325,  304,
      327,  328,  997,  997,    0,  997,  997,  997,  997,  997,
      997,  997,  851,  362,    0,  997,  997,  997,  997,  997,
      997,  849,  369,    0,  894,  382,  997,    0,  904,  852,
      854,  997,  292,  118,  879,    0,  880,  393,  365,  871,
        0,  382,  394,    0,    0,  870,  866,  418,  864,  859,
      422,  424,  997,  997,  330,  350,  404,  418,  419,  424,

      425,  427,  426,  431,  874,  873,  428,  868,  866,  865,
      437,  863,  438,  441,  860,  442,  859,  858,  857,  439,
      440,  443,  444,  445,  446,  447,  449,  448,  856,  451,
      455,    0,    0,    0,    0,  132,  814,  489,  807,  824,
      458,  437,  497,  424,  348,  823,  799,    0,  822,    0,
        0,  821,  820,  819,  475,  815,  491,  813,  469,  495,
      459,  812,  810,  492,  460,  795,  793,  497,  761,  519,
      757,  520,  521,  524,  525,  750,  741,  526,  528,  529,
      704,  997,  697,  997,  532,  997,  683,  997,  530,  519,
      571,    0,  578,  673,  997,  668,  688,  691,  690,  689,

      535,  629,  627,  552,  626,  553,  625,  624,  555,  538,
      527,  623,  622,  541,  621,  620,  583,  582,  581,  580,
      562,  547,  593,    0,  533,  555,    0,    0,    0,  572,
      560,  571,  566,  542,  458,  351,  313,  312,  301,  291,
      202,  997,  579,  502,  183,  522,  180,   92,  116,  569,
      997,  570,  997,  997,  997,  635,  653,  671,  689,  704,
      722,  740,  758,  776,  794,  803,  820,  830,  838,  457,
      855,  856,  864,  872,  881,  889,  898,  906,  552,  915,
      923,  931,  939,  947,  955,  963,  971,  979
    } ;

static yyconst short int yy_def[389] =
    {   0,
      355,    1,  356,  356,  357,  357,  358,  358,  359,  359,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,   28,  355,
      355,  355,  355,  355,  360,  360,  355,  355,  355,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  355,  355,  355,  361,  355,  355,  362,
      355,  355,  355,  363,  355,  364,  365,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      366,  355,  367,  355,  355,  368,   28,  369,  369,  369,
      369,  369,  369,  369,  369,  355,  355,  355,  355,  355,

      355,  355,  360,  360,  360,  355,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  355,  355,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  355,  355,  361,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  362,  355,  355,  355,  355,  355,
      355,  355,  355,  363,  364,  364,  355,  365,  355,  355,
      355,  355,  366,  370,  355,  367,  355,  371,  372,  355,
      369,  355,  369,   90,   89,  369,  369,  369,  369,  369,
       94,   95,  355,  355,  360,  360,  360,  360,  360,  360,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  373,  374,  375,  376,  355,  355,  355,  377,  355,
      371,  378,  355,  372,  379,  355,  380,  183,  369,  369,
      369,  369,  369,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      381,  355,  382,  355,  355,  355,  377,  355,  355,  355,
      355,  383,  355,  384,  355,  380,  355,  369,  369,  369,

      360,  360,  360,  360,  360,  360,  360,  360,  360,  360,
      360,  360,  360,  360,  360,  360,  385,  381,  386,  382,
      355,  355,  355,  383,  384,  355,  369,  369,  369,  360,
      360,  360,  360,  360,  360,  360,  387,  385,  388,  386,
      355,  355,  360,  355,  387,  355,  388,  355,  360,  355,
      355,  355,  355,  355,    0,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355
    } ;

static yyconst short int yy_nxt[1063] =
    {   0,
       12,   13,   14,   15,   16,   12,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   29,
       29,   29,   29,   29,   29,   30,   31,   32,   33,   34,
       35,   35,   35,   36,   37,   12,   38,   39,   35,   40,
       41,   42,   35,   43,   44,   35,   35,   45,   35,   46,
       47,   35,   35,   48,   49,   50,   51,   52,   35,   53,
       35,   35,   54,   55,   56,   58,   58,   61,   61,   62,
       62,   65,   65,   68,   68,   69,   69,   72,   78,   79,
       66,   66,   80,   88,   81,   81,   81,   81,   81,   81,
       81,   81,   59,   59,   82,   88,   97,   98,   73,   83,

       63,   63,  102,   88,  100,  101,  102,  166,  178,  102,
      102,   84,  167,  102,  188,  188,  174,   85,   85,  102,
       74,  102,  102,  132,  133,   75,   85,   85,  174,  175,
      238,  177,  238,  285,  285,  188,  354,  180,  205,  206,
       86,  102,   87,   87,   87,   87,   87,   87,   87,   87,
      102,  102,  142,  126,  107,   88,   89,   88,   88,  108,
      131,  109,  127,   90,   88,   91,   88,   88,   89,   92,
       88,   88,   93,   88,   88,   88,   88,   94,   88,   88,
       88,   88,   88,   88,   88,   95,   88,  113,  102,  114,
      104,  102,  102,  102,  110,  102,  132,  133,  115,  102,

      111,  102,  112,  105,  102,  116,  143,  102,  117,  121,
       88,  102,  122,  102,  102,  146,  102,  102,  347,  147,
      102,  345,   88,  102,  118,  156,  102,  102,  148,  128,
       88,  135,  102,  123,  102,  134,  119,  120,  157,  124,
      125,  144,  129,  199,  136,  137,  149,  130,  102,  140,
      138,  348,  102,  141,  198,  196,  158,  139,  102,  195,
      197,  102,  150,  201,  200,  151,  210,  152,  153,  202,
      102,  154,  159,  102,  203,  160,  204,  161,  162,  212,
      207,  163,  182,  208,  182,  102,  209,  183,  183,  183,
      183,  183,  183,  183,  183,   85,   85,  102,  191,  191,

      191,  191,  191,  191,  191,  214,  102,  102,  211,   86,
      213,  184,  184,  184,  184,  184,  184,  184,  184,  191,
      102,  102,  102,  174,  215,  185,  217,  102,  102,  340,
      102,  102,  184,  102,  218,  174,  175,  185,  186,  347,
      216,  187,  192,  192,  192,  192,  192,  192,  192,  192,
      338,  345,  221,  102,  102,  192,  192,  222,  225,  228,
      293,  219,  293,  192,  192,  192,  192,  192,  192,  192,
      229,  230,  223,  220,  254,  231,  226,  224,  227,  233,
      233,  233,  233,  233,  233,  233,  235,  235,  235,  235,
      235,  235,  235,  166,  241,  241,  245,  255,  167,  247,

      247,  247,  247,  247,  247,  247,  247,  102,  245,  180,
      242,  248,  248,  248,  248,  248,  248,  248,  248,   85,
       85,  102,  102,   85,   85,   85,   85,  102,  102,  102,
      102,  102,  248,  177,  102,  188,  188,  177,  186,  177,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  256,  102,  245,  188,  257,  102,  241,
      241,  102,  102,  102,  239,  249,  239,  245,  180,  252,
      262,  253,  102,  258,  264,  242,  263,  290,  102,  259,
      260,  261,  268,  265,  271,  269,  266,  278,  274,  291,
      276,  267,  277,  275,  102,  102,  270,  292,  102,  272,

      102,  273,  305,  307,  280,  279,  239,  239,  239,  239,
      239,  239,  239,  239,  289,  289,  289,  289,  289,  289,
      289,  289,  102,  102,  102,  303,  301,  102,  102,  102,
      102,  102,  102,  285,  285,  289,  322,  322,  102,  302,
      350,  102,  304,  308,  102,  102,  306,  289,  289,  289,
      289,  289,  289,  289,  289,  102,  102,  322,  102,  294,
      352,  294,  311,  102,  322,  322,  351,  310,  289,  102,
      314,  315,  316,  309,  102,  102,  342,  180,  312,  334,
      330,  313,  102,  335,  336,  322,  353,  321,  323,  323,
      323,  323,  323,  323,  323,  294,  294,  294,  294,  294,

      294,  294,  294,  331,  332,  341,  333,  350,  352,  323,
      323,  323,  323,  323,  323,  323,  323,  343,  320,  340,
      318,  338,  349,  102,  102,  102,  102,  102,  102,  102,
      102,  323,  102,  351,  353,   57,   57,   57,   57,   57,
       57,   57,   57,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   57,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,

       67,   67,   67,   67,   67,   67,   67,  103,  329,  328,
      327,  326,  297,  103,  103,  103,  103,  180,  103,  103,
      103,  103,  145,  145,  145,  145,  145,  175,  145,  145,
      145,  145,  145,  145,  145,  320,  145,  145,  145,  145,
      155,  155,  318,  155,  102,  155,  155,  155,  155,  155,
      155,  155,  155,  102,  155,  155,  155,  155,  164,  164,
      102,  164,  164,  164,  102,  164,  164,  164,  164,  164,
      164,  164,  164,  164,  164,  164,  165,  165,  165,  165,
      165,  165,  165,  165,  165,  165,  165,  165,  165,  165,
      165,  165,  165,  165,  168,  168,  102,  168,  102,  168,

      168,  168,  168,  168,  168,  168,  168,  168,  168,  168,
      168,  168,  173,  102,  173,  102,  102,  173,  102,  173,
      176,  176,  102,  176,  176,  176,  176,  176,  176,  176,
      176,  176,  176,  176,  176,  176,  176,  176,  179,  179,
      300,  299,  298,  297,  295,  288,  179,  181,  181,  181,
      181,  175,  181,  181,  181,  181,  243,  243,  286,  102,
      102,  102,  102,  102,  243,  244,  102,  244,  102,  102,
      244,  102,  244,  281,  281,  281,  102,  102,  251,  281,
      281,  282,  282,  282,  282,  250,  190,  282,  282,  282,
      283,  283,  283,  189,  246,  178,  283,  283,  284,  284,

      284,  284,  240,  237,  284,  284,  284,  287,  236,  169,
      355,  234,  287,  232,  287,  289,  102,  102,  102,  102,
      289,  289,  102,  289,  296,  194,  193,  190,  189,  296,
      172,  296,  317,  317,  317,  171,  170,  317,  317,  317,
      319,  319,  319,  169,  106,  319,  319,  319,  324,  324,
      324,  102,   99,  324,  324,  324,  325,   96,   77,   76,
       71,  325,   70,  325,  337,  337,  337,  355,  355,  337,
      337,  337,  339,  339,  339,  355,  355,  339,  339,  339,
      344,  344,  344,  355,  355,  344,  344,  344,  346,  346,
      346,  355,  355,  346,  346,  346,   11,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355
    } ;

static yyconst short int yy_chk[1063] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    4,    5,    6,    5,
        6,    7,    8,    9,   10,    9,   10,   18,   25,   25,
        7,    8,   26,   29,   26,   26,   26,   26,   26,   26,
       26,   26,    3,    4,   27,   29,   32,   32,   18,   27,

        5,    6,   40,   29,   34,   34,   48,   66,   86,   53,
       41,   27,   66,   46,   91,   91,   81,   85,   85,  349,
       18,  117,  116,  133,  133,   18,   28,   28,   81,   81,
      174,   85,  174,  236,  236,   91,  348,   86,  116,  117,
       28,   43,   28,   28,   28,   28,   28,   28,   28,   28,
       36,   42,   53,   46,   40,   28,   28,   28,   28,   41,
       48,   41,   46,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   43,   44,   43,
       36,   50,   45,   47,   42,   49,   49,   49,   43,   51,

       42,   52,   42,   36,  105,   44,   55,  110,   44,   45,
       87,  108,   45,  104,  109,   59,  111,  113,  347,   59,
      114,  345,   87,  115,   44,   63,  126,  112,   59,   47,
       87,   50,  120,   45,  118,   49,   44,   44,   63,   45,
       45,   55,   47,  110,   50,   50,   59,   47,  122,   52,
       51,  341,  128,   52,  109,  105,   63,   51,  124,  104,
      108,  127,   59,  112,  111,   59,  122,   59,   59,  113,
      121,   59,   63,  130,  114,   63,  115,   63,   63,  126,
      118,   63,   89,  120,   89,  129,  121,   89,   89,   89,
       89,   89,   89,   89,   89,   90,   90,  131,   94,   94,

       94,   94,   94,   94,   94,  128,  135,  140,  124,   90,
      127,   90,   90,   90,   90,   90,   90,   90,   90,   94,
      134,  136,  138,  173,  129,   90,  130,  137,  139,  340,
      141,  142,   90,  195,  131,  173,  173,   90,   90,  339,
      129,   90,   95,   95,   95,   95,   95,   95,   95,   95,
      338,  337,  135,  196,  336,   95,   95,  136,  138,  140,
      245,  134,  245,   95,   95,   95,   95,   95,   95,   95,
      141,  142,  136,  134,  195,  142,  138,  137,  139,  154,
      154,  154,  154,  154,  154,  154,  163,  163,  163,  163,
      163,  163,  163,  166,  178,  178,  179,  196,  166,  182,

      182,  182,  182,  182,  182,  182,  182,  197,  179,  179,
      178,  183,  183,  183,  183,  183,  183,  183,  183,  188,
      188,  198,  199,  191,  191,  192,  192,  200,  201,  203,
      202,  207,  183,  188,  204,  188,  188,  191,  183,  192,
      211,  213,  220,  221,  214,  216,  222,  223,  224,  225,
      226,  228,  227,  197,  230,  244,  188,  198,  231,  241,
      241,  335,  261,  265,  370,  188,  370,  244,  244,  191,
      202,  192,  259,  199,  204,  241,  203,  242,  255,  200,
      200,  201,  214,  207,  221,  216,  211,  228,  224,  242,
      226,  213,  227,  225,  257,  264,  220,  242,  260,  222,

      268,  223,  261,  265,  231,  230,  238,  238,  238,  238,
      238,  238,  238,  238,  243,  243,  243,  243,  243,  243,
      243,  243,  270,  272,  273,  259,  255,  274,  275,  278,
      311,  279,  280,  285,  285,  243,  290,  290,  301,  257,
      344,  310,  260,  268,  314,  334,  264,  289,  289,  289,
      289,  289,  289,  289,  289,  304,  306,  290,  309,  379,
      346,  379,  273,  331,  322,  322,  344,  272,  289,  333,
      278,  279,  280,  270,  332,  330,  326,  325,  274,  310,
      301,  275,  343,  311,  314,  322,  346,  285,  291,  291,
      291,  291,  291,  291,  291,  293,  293,  293,  293,  293,

      293,  293,  293,  304,  306,  321,  309,  350,  352,  291,
      323,  323,  323,  323,  323,  323,  323,  331,  320,  319,
      318,  317,  343,  316,  315,  313,  312,  308,  307,  305,
      303,  323,  302,  350,  352,  356,  356,  356,  356,  356,
      356,  356,  356,  356,  356,  356,  356,  356,  356,  356,
      356,  356,  356,  357,  357,  357,  357,  357,  357,  357,
      357,  357,  357,  357,  357,  357,  357,  357,  357,  357,
      357,  358,  358,  358,  358,  358,  358,  358,  358,  358,
      358,  358,  358,  358,  358,  358,  358,  358,  358,  359,
      359,  359,  359,  359,  359,  359,  359,  359,  359,  359,

      359,  359,  359,  359,  359,  359,  359,  360,  300,  299,
      298,  297,  296,  360,  360,  360,  360,  294,  360,  360,
      360,  360,  361,  361,  361,  361,  361,  287,  361,  361,
      361,  361,  361,  361,  361,  283,  361,  361,  361,  361,
      362,  362,  281,  362,  277,  362,  362,  362,  362,  362,
      362,  362,  362,  276,  362,  362,  362,  362,  363,  363,
      271,  363,  363,  363,  269,  363,  363,  363,  363,  363,
      363,  363,  363,  363,  363,  363,  364,  364,  364,  364,
      364,  364,  364,  364,  364,  364,  364,  364,  364,  364,
      364,  364,  364,  364,  365,  365,  267,  365,  266,  365,

      365,  365,  365,  365,  365,  365,  365,  365,  365,  365,
      365,  365,  366,  263,  366,  262,  258,  366,  256,  366,
      367,  367,  254,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  368,  368,
      253,  252,  249,  247,  246,  240,  368,  369,  369,  369,
      369,  239,  369,  369,  369,  369,  371,  371,  237,  229,
      219,  218,  217,  215,  371,  372,  212,  372,  210,  209,
      372,  208,  372,  373,  373,  373,  206,  205,  190,  373,
      373,  374,  374,  374,  374,  189,  187,  374,  374,  374,
      375,  375,  375,  186,  180,  177,  375,  375,  376,  376,

      376,  376,  175,  171,  376,  376,  376,  377,  170,  169,
      165,  162,  377,  153,  377,  378,  125,  123,  119,  107,
      378,  378,  103,  378,  380,  101,   97,   93,   92,  380,
       80,  380,  381,  381,  381,   75,   74,  381,  381,  381,
      382,  382,  382,   69,   39,  382,  382,  382,  383,  383,
      383,   35,   33,  383,  383,  383,  384,   30,   23,   22,
       17,  384,   15,  384,  385,  385,  385,   11,    0,  385,
      385,  385,  386,  386,  386,    0,    0,  386,  386,  386,
      387,  387,  387,    0,    0,  387,  387,  387,  388,  388,
      388,    0,    0,  388,  388,  388,  355,  355,  355,  355,

      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355,  355,  355,  355,  355,  355,  355,  355,  355,
      355,  355
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lex.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define CHAR 1

#define STRING 2

#define ML_COMMENT 3

#define SHIELD_STRING 4

#line 12 "lex.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <iostream>
    #include <string>
    #include <ctype.h>
    using namespace std;

    void removeUnderline(char str[]);
    void removeType(char str[], char *typeName);
    void convertCharacterCodeToString(char characterCode[], int startPosition, char *string);
    int translateNumberByBase(char *input_string);
    void removeSpacesAndUnderlines(char* input);
    int findRightNumberPos(const char *input_string);
    int findSecondDot(const char *input_string);
#line 747 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 29 "lex.l"



    char str[1024];
    string stdstr = "";
    int lineNumber = 1;
    int octothorpeCount = 0;


#line 904 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 356 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 997 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 38 "lex.l"
{ lineNumber++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "lex.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lex.l"
{ printf("Found KW_AS: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 42 "lex.l"
{ printf("Found KW_BREAK: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 43 "lex.l"
{ printf("Found KW_CONST: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 44 "lex.l"
{ printf("Found KW_CONTINUE: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 45 "lex.l"
{ printf("Found KW_CRATE: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 46 "lex.l"
{ printf("Found KW_ELSE: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 47 "lex.l"
{ printf("Found KW_ENUM: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 48 "lex.l"
{ printf("Found KW_EXTERN: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 49 "lex.l"
{ printf("Found KW_FALSE: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "lex.l"
{ printf("Found KW_FN: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "lex.l"
{ printf("Found KW_FOR: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 52 "lex.l"
{ printf("Found KW_IF: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 53 "lex.l"
{ printf("Found KW_IMPL: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 54 "lex.l"
{ printf("Found KW_IN: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 55 "lex.l"
{ printf("Found KW_LET: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 56 "lex.l"
{ printf("Found KW_LOOP: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 57 "lex.l"
{ printf("Found KW_MATCH: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 58 "lex.l"
{ printf("Found KW_MOD: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 59 "lex.l"
{ printf("Found KW_MOVE: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "lex.l"
{ printf("Found KW_MUT: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 61 "lex.l"
{ printf("Found KW_PUB: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 62 "lex.l"
{ printf("Found KW_REF: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 63 "lex.l"
{ printf("Found KW_RETURN: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 64 "lex.l"
{ printf("Found KW_SELFVALUE: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 65 "lex.l"
{ printf("Found KW_SELFTYPE: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 66 "lex.l"
{ printf("Found KW_STATIC: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 67 "lex.l"
{ printf("Found KW_STRUCT: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 68 "lex.l"
{ printf("Found KW_SUPER: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 69 "lex.l"
{ printf("Found KW_TRAIT: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 70 "lex.l"
{ printf("Found KW_TRUE: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 71 "lex.l"
{ printf("Found KW_TYPE: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 72 "lex.l"
{ printf("Found KW_UNSAFE: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 73 "lex.l"
{ printf("Found KW_USE: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 74 "lex.l"
{ printf("Found KW_WHERE: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 75 "lex.l"
{ printf("Found KW_WHILE: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 76 "lex.l"
{ printf("Found KW_MUT_REF: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 77 "lex.l"
{ printf("Found KW_SELF_REF: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 78 "lex.l"
{ printf("Found KW_MUT_SELF_REF: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 80 "lex.l"
{ printf("Found TYPE_BOOL: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 81 "lex.l"
{ printf("Found TYPE_I32: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 82 "lex.l"
{ printf("Found TYPE_I64: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 83 "lex.l"
{ printf("Found TYPE_F32: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 84 "lex.l"
{ printf("Found TYPE_F64: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 85 "lex.l"
{ printf("Found TYPE_STRING: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 86 "lex.l"
{ printf("Found TYPE_CHAR: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 89 "lex.l"
{ printf("Found OPERATOR_PLUS: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 90 "lex.l"
{ printf("Found OPERATOR_MINUS: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 91 "lex.l"
{ printf("Found OPERATOR_MUL: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 92 "lex.l"
{ printf("Found OPERATOR_DIV: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 93 "lex.l"
{ printf("Found OPERATOR_MOD: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 95 "lex.l"
{ printf("Found OPERATOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 96 "lex.l"
{ printf("Found OPERATOR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 97 "lex.l"
{ printf("Found OPERATOR_NOT_EQUAL: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 98 "lex.l"
{ printf("Found OPERATOR_LESS: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 99 "lex.l"
{ printf("Found OPERATOR_MORE: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 100 "lex.l"
{ printf("Found OPERATOR_LESS_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 101 "lex.l"
{ printf("Found OPERATOR_MORE_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 103 "lex.l"
{ printf("Found OPERATOR_AMPERSAND: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 104 "lex.l"
{ printf("Found OPERATOR_BIT_OR: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 105 "lex.l"
{ printf("Found OPERATOR_BIT_NOT: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 106 "lex.l"
{ printf("Found OPERATOR_BIT_XOR: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 107 "lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 108 "lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 110 "lex.l"
{ printf("Found OPERATOR_AND: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 111 "lex.l"
{ printf("Found OPERATOR_OR: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "lex.l"
{ printf("Found OPERATOR_PLUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "lex.l"
{ printf("Found OPERATOR_MINUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "lex.l"
{ printf("Found OPERATOR_MUL_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "lex.l"
{ printf("Found OPERATOR_DIV_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 117 "lex.l"
{ printf("Found OPERATOR_MOD_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 118 "lex.l"
{ printf("Found OPERATOR_BIT_AND_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 119 "lex.l"
{ printf("Found OPERATOR_BIT_OR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 120 "lex.l"
{ printf("Found OPERATOR_BIT_XOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 121 "lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 122 "lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 124 "lex.l"
{ printf("Found OPERATOR_POINT: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 125 "lex.l"
{ printf("Found OPERATOR_RANGE: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 126 "lex.l"
{ printf("Found OPERATOR_RANGE_ASSIGMENT: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 127 "lex.l"
{ printf("Found OPERATOR_ARROW: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 129 "lex.l"
{ printf("Found LEFT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 130 "lex.l"
{ printf("Found RIGHT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 131 "lex.l"
{ printf("Found LEFT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 132 "lex.l"
{ printf("Found RIGHT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 133 "lex.l"
{ printf("Found LEFT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 134 "lex.l"
{ printf("Found RIGHT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 136 "lex.l"
{ printf("Found COMMA: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 137 "lex.l"
{ printf("Found SEMICOLON: %s\n", yytext); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 138 "lex.l"
{ printf("Found COLON: %s\n", yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 139 "lex.l"
{ printf("Found TWO_COLON: %s\n", yytext); }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 142 "lex.l"
{ strcpy(str,""); BEGIN(ML_COMMENT); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 143 "lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 144 "lex.l"
{ lineNumber++; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 145 "lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 146 "lex.l"
{ printf("Found ML_COMMENT: %s\n", str);  BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 147 "lex.l"
{ printf("ML_COMMENT Error in line %d: comment are not closed\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 149 "lex.l"
{ printf("Found COMMENT: %s\n", yytext); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 151 "lex.l"
{ stdstr = ""; BEGIN(STRING); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 152 "lex.l"
{ stdstr += yytext; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 153 "lex.l"
{ lineNumber++; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 154 "lex.l"
{ stdstr += "\n"; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 155 "lex.l"
{ stdstr += "\r"; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 156 "lex.l"
{ stdstr += "\t"; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 157 "lex.l"
{ stdstr.push_back('\0'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 158 "lex.l"
{ stdstr += "\\"; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 159 "lex.l"
{ stdstr += "\""; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 160 "lex.l"
{
    int x = strtol(yytext + 3,NULL, 16); 
    if(x <= 127)
    {
        char tmp[2];
        tmp[0] = x;
        tmp[1] = 0;
        stdstr += tmp;
    }
    else
    {
     printf("CHAR Error in line %d: Unicode is not support\n", lineNumber);
    }
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 174 "lex.l"
{
    char string[2];
    convertCharacterCodeToString(yytext, 2, string);
    stdstr += string;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 179 "lex.l"
{ cout << "Found STRING: " << stdstr << endl; BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 180 "lex.l"
{ printf("STRING Error in line %d: there is no closing quotation mark\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 181 "lex.l"
{ printf("STRING Error in line %d: slash\n", lineNumber); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 183 "lex.l"
{stdstr = ""; octothorpeCount = strlen(yytext) - 2; BEGIN(SHIELD_STRING);}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 184 "lex.l"
{ stdstr += yytext; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 185 "lex.l"
{ stdstr += "\n"; lineNumber++; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 186 "lex.l"
{
    int tmp  = strlen(yytext) - 1;
    if(tmp == octothorpeCount)
    {
        cout << "Found STRING: " << stdstr << endl; BEGIN(INITIAL);
    }
    else
    {
         stdstr += yytext;
    }

}
	YY_BREAK
case YY_STATE_EOF(SHIELD_STRING):
#line 198 "lex.l"
{ printf("SHIELD_STRING Error in line %d: there is no closing quotation mark\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 201 "lex.l"
{ stdstr = ""; BEGIN(CHAR); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 202 "lex.l"
{ stdstr += yytext; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 203 "lex.l"
{ stdstr += "\n"; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 204 "lex.l"
{ stdstr += "\r"; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 205 "lex.l"
{ stdstr += "\t"; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 206 "lex.l"
{ stdstr.push_back('\0'); }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 207 "lex.l"
{ stdstr += "\\"; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 208 "lex.l"
{ stdstr += "\'"; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 209 "lex.l"
{ stdstr += "\""; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 210 "lex.l"
{
    int x = strtol(yytext + 3,NULL, 16);
    if(x <= 127)
    {
        char tmp[2];
        tmp[0] = x;
        tmp[1] = 0;
        stdstr += tmp;
    }
    else
    {
     printf("CHAR Error in line %d: Unicode is not support\n", lineNumber);
    }
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 224 "lex.l"
{
    char string[2];
    convertCharacterCodeToString(yytext, 2, string);
    stdstr += string;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 229 "lex.l"
{
    if(stdstr.size() == 1) {
        cout << "Found CHAR:  " << stdstr << endl;
    }
    else if(stdstr.size() == 0)
    {
        printf("CHAR Error in line %d: empty char literal\n", lineNumber);
    }
    else
    {
        printf("CHAR Error in line %d: more than one char in quote\n", lineNumber);
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 243 "lex.l"
{ printf("CHAR Error in line %d: there is no closing quotation mark\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 244 "lex.l"
{ printf("CHAR Error in line %d: slash\n", lineNumber); }
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 246 "lex.l"
{

    strcpy(str, yytext);
    int second_dot_index = findSecondDot(str);
    int first_dot_index = second_dot_index - 1;
    int right_number_index = findRightNumberPos(&str[second_dot_index]) + second_dot_index;

    char left_number[50];
    char right_number[50];

    strncpy(left_number, str + 0, first_dot_index);
    left_number[first_dot_index] = '\0';

    int length = strlen(str) - right_number_index;
    strncpy(right_number, str + right_number_index, length);
    right_number[length] = '\0';

    translateNumberByBase(left_number);
    translateNumberByBase(right_number);
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 267 "lex.l"
{

    removeType(str, "i32");
    removeUnderline(str);
    printf("Found DECIMAL_NUMBER: %d\n", atoi(str));
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 274 "lex.l"
{

    removeType(str, "i32");
    removeUnderline(str);
    if(strlen(str) > 2)
    {
         printf("Found BIN_NUMBER: %d\n", strtol(str + 2, NULL, 2));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 288 "lex.l"
{

    removeType(str, "i32");
    removeUnderline(str);
    if(strlen(str) > 2)
    {
         printf("Found OCTAL_NUMBER: %d\n", strtol(str + 2, NULL, 8));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 302 "lex.l"
{

    removeType(str, "i32");
    removeUnderline(str);
    if(strlen(str) > 2)
    {
         printf("Found HEXADECIMAL_NUMBER: %d\n", strtol(str + 2, NULL, 16));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 316 "lex.l"
{
    printf("INCORRECT DOUBLE Error in line %d: float literals must have an integer part", lineNumber);
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 320 "lex.l"
{
    removeType(str, "f64");
    removeUnderline(str);
    printf("Found DOUBLE: %lf\n", atof(str), str);
}
	YY_BREAK
case 135:
YY_RULE_SETUP
#line 326 "lex.l"
{
    removeType(str, "f64");
    removeUnderline(str);
    printf("Found DOUBLE: %lf\n", atof(str));
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 332 "lex.l"
{ printf("Found IDENTIFIER: %s\n", yytext);}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 333 "lex.l"
{ printf("Found MACROS: %s\n", yytext);}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 334 "lex.l"
{ printf("Error in line %d: incorrect IDENTIFIER\n", lineNumber); }
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 335 "lex.l"
{ printf("Error in line %d: incorrect character in code\n", lineNumber); }
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 336 "lex.l"
ECHO;
	YY_BREAK
#line 1831 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 356 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 356 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 355);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 336 "lex.l"


void convertCharacterCodeToString(char characterCode[], int startPosition, char *string)
{
    string[0] = strtol(characterCode + startPosition,NULL, 16);
    string[1] = '\0';
}

void removeUnderline(char str[])
{
  int pos = 0;
  for(int i = 0; i < strlen(yytext); i++)
  {
        if(yytext[i] != '_')
        {
            str[pos++] = yytext[i];
        }
  }

  str[pos] = '\0';
  strcpy(yytext, str);
}

void removeType(char str[], char *typeName)
{
    strcpy(str, yytext);
    char* p = strstr(str, typeName);
    if(p != NULL)
    {
        int pos = strlen(str)  - strlen(typeName);
        str[pos] = 0;
    }
}

int findSecondDot(const char *input_string) {
    int first_dot = -1;  // Переменная для индекса первой точки

    for (int i = 0; input_string[i] != '\0'; i++) {
        if (input_string[i] == '.') {
            if (first_dot == -1) {
                first_dot = i;  // Нашли первую точку
            } else {
                printf("Found TWO_DOTS: %.*s\n", i - first_dot + 1, input_string + first_dot);
                return i;  // Нашли вторую точку, возвращаем её индекс
            }
        }
    }

    return -1;  // Второй символ точки не найден
}

int findRightNumberPos(const char *input_string) {

    for (int i = 0; input_string[i] != '\0'; i++) {
        if (input_string[i] >= '0' && input_string[i] <= '9') {
            return i;  // Нашли индекс начала второго числа
        }
    }

    return -1;  // второе число не нашлось
}

void removeSpacesAndUnderlines(char* input) {
    int len = strlen(input);
    int i, j = 0;

    for (i = 0; i < len; i++) {
        if (input[i] != ' ' && input[i] != '_') {
            input[j] = input[i];
            j++;
        }
    }
    input[j] = '\0';
}

int translateNumberByBase(char *input_string) {
    removeSpacesAndUnderlines(input_string);
    int len = strlen(input_string);

    if (len == 1 && (input_string[0] >= '0' && input_string[0] <= '9')) {
        printf("Found RANGE_DECIMAL_NUMBER: %d\n", atoi(input_string));
    } else if (len >= 2 && (input_string[0] >= '0' && input_string[0] <= '9') && (input_string[1] >= '0' && input_string[1] <= '9')) {
        printf("Found RANGE_DECIMAL_NUMBER: %d\n", atoi(input_string));
    }


    if (input_string[0] == '0' && (len > 2)){
        if (input_string[1] == 'x'){
            printf("Found RANGE_HEXADECIMAL_NUMBER: %ld\n", strtol(input_string + 2, NULL, 16));
        } else if (input_string[1] == 'b') {
            printf("Found RANGE_BIN_NUMBER: %ld\n", strtol(input_string + 2, NULL, 2));
        } else if (input_string[1] == 'o'){
            printf("Found RANGE_OCTAL_NUMBER: %ld\n", strtol(input_string + 2, NULL, 8));
        } else {
            printf("Found RANGE_DECIMAL_NUMBER: %d\n", atoi(input_string));
        }
    }

    return -1; // не удалось произвести операцию перевода с числом
}

int main(int argc, char** argv) {

    if (argc != 2) {
        printf("Filename is not found");
        return 1;
    }

    const char *filename= argv[1];
    
    FILE *file = fopen(filename, "r");
    if (file == NULL) {
        printf("File opening error");
        return 1;
    }

    yyin = file;
    yylex();
    fclose(file);

    return 0;
}


