/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 129
#define YY_END_OF_BUFFER 130
static yyconst short int yy_accept[304] =
    {   0,
        0,    0,    0,    0,    0,    0,   90,   90,  130,  129,
        1,    2,   59,   95,   49,   57,  108,   79,   80,   47,
       45,   85,   46,   75,   48,  120,  120,   87,   86,   53,
       50,   54,  126,  126,   81,   82,   60,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,   83,   58,   84,  109,  118,  119,   96,   97,  106,
      107,   90,   91,   92,   52,   69,   63,   70,   67,   65,
       66,   78,   76,   89,   94,   68,  124,  120,  128,  128,
      120,  128,  128,  128,  128,  128,   88,   61,   55,   51,
       56,   62,  127,  126,  126,  126,   72,    3,  126,  126,

      126,  126,  126,  126,  126,  126,  126,  126,  126,   12,
      126,  126,  126,   14,  126,   16,  126,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  126,
      126,   71,   64,  109,  115,  113,  114,  110,  111,  112,
        0,    0,   96,  103,  101,  102,   98,   99,  100,    0,
        0,   90,   92,   92,   93,   77,   94,  124,    0,  128,
        0,  125,  120,  128,  128,  128,  121,  128,  128,  122,
      123,   73,   74,  126,  126,  126,  126,  126,  126,  126,
      126,  126,  126,   41,   42,  126,   13,   39,   40,  126,
       17,  126,  126,   20,  126,   22,   23,   24,  126,  126,

      126,  126,  126,  126,  126,  126,  126,   35,  126,  126,
        0,    0,    0,    0,  124,    0,    0,  125,  125,  128,
      125,  120,  128,  128,   27,  126,   38,  126,   44,  126,
      126,  126,    8,    9,  126,  126,   15,   18,  126,   21,
      126,   26,  126,  126,  126,  126,   32,   33,  126,  126,
      126,    0,  117,    0,  105,    0,  124,  124,  125,    0,
      128,  128,  128,  126,    4,    5,  126,    7,  126,   11,
       19,  126,  126,  126,   30,   31,  126,   36,   37,    0,
        0,  124,    0,  121,  122,  123,   43,  126,   10,   25,
       28,   29,   34,    0,    0,  125,  126,    0,    0,    6,

      116,  104,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   24,   25,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   33,   32,   32,   32,   32,   32,   32,   32,
       34,   35,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       61,   32,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    2,    1,    3,    4,    1,    1,    5,    1,    1,
        6,    7,    1,    7,    1,    1,    8,    8,    8,    8,
        8,    8,    8,    8,    1,    1,    1,    1,    1,    9,
       10,   11,   11,    1,   12,    1,    1,   13,    9,    9,
        9,    9,   10,   14,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,    1,    1,    1
    } ;

static yyconst short int yy_base[328] =
    {   0,
        0,    0,   57,   58,   65,   66,   67,   70,  739,  750,
      750,  750,  706,  750,  705,   66,  750,  750,  750,  704,
      699,  750,   46,  711,   68,   87,   37,  700,  750,   55,
      691,   57,  714,  108,  750,  750,  689,   94,  109,  119,
      117,  149,  155,   72,  146,   95,  112,  152,  150,  163,
       76,  750,  129,  750,    0,  750,  172,    0,  750,  750,
      185,    0,  750,   79,  750,  750,  750,  750,  750,  750,
      750,  750,  688,  750,    0,  750,  229,  122,    0,  262,
      272,  179,  690,  692,  237,  303,  750,  683,  750,  750,
      750,  678,  750,  701,  166,  156,  750,  700,  172,  179,

      154,  180,  177,  175,  183,  182,   84,  223,  215,  694,
      208,  259,  267,  693,  190,  692,  209,  217,  221,  293,
      257,  230,  262,  263,  298,  264,  297,  295,  294,  229,
      310,  750,  750,    0,  750,  750,  750,  750,  750,  750,
      633,  341,    0,  750,  750,  750,  750,  750,  750,  630,
      348,    0,  675,  289,  750,  750,    0,  341,  662,    0,
      356,  369,    0,    0,  661,  663,  291,  657,  658,  624,
      623,  750,  750,  351,  303,  307,  300,  327,  378,  379,
      393,  187,  394,  665,  659,  390,  658,  656,  652,  392,
      635,  395,  397,  611,  396,  607,  603,  595,  398,  399,

      400,  401,  404,  402,  407,  408,  405,  593,  406,  410,
        0,    0,    0,    0,  384,  316,  572,  542,    0,  559,
        0,    0,  554,  553,  568,  412,  567,  413,  522,  414,
      415,  421,  521,  520,  417,  422,  519,  518,  420,  517,
      418,  516,  426,  416,  425,  419,  514,  513,  436,  438,
      442,    0,  750,    0,  750,  469,  472,  750,  470,  490,
      493,  492,  491,  449,  505,  504,  427,  502,  448,  501,
      500,  450,  428,  463,  499,  498,  464,  496,  494,    0,
        0,  453,  475,    0,    0,    0,  491,  470,  480,  473,
      336,  328,  231,    0,    0,  750,  472,   50,   27,   83,

      750,  750,  750,  527,  541,  555,  567,  581,  595,  609,
      623,  637,  644,  651,  658,  665,  672,  679,  475,  686,
      693,  700,  707,  714,  721,  728,  735
    } ;

static yyconst short int yy_def[328] =
    {   0,
      303,    1,  304,  304,  305,  305,  306,  306,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,   26,  303,  303,  303,
      303,  303,  307,  307,  303,  303,  303,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  303,  303,  303,  308,  303,  303,  309,  303,  303,
      303,  310,  303,  311,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  312,  303,  303,   26,  313,  313,
      313,  313,  313,  313,  313,  313,  303,  303,  303,  303,
      303,  303,  303,  307,  307,  307,  303,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  303,  303,  308,  303,  303,  303,  303,  303,  303,
      303,  303,  309,  303,  303,  303,  303,  303,  303,  303,
      303,  310,  311,  311,  303,  303,  312,  314,  303,  313,
      303,  313,   81,   80,  313,  313,  313,  313,  313,   85,
       86,  303,  303,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,

      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      315,  316,  317,  318,  314,  319,  303,  320,  162,  313,
      313,  313,  313,  313,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  307,
      307,  321,  303,  322,  303,  303,  323,  303,  320,  303,
      313,  313,  313,  307,  307,  307,  307,  307,  307,  307,
      307,  307,  307,  307,  307,  307,  307,  307,  307,  324,
      325,  323,  303,  313,  313,  313,  307,  307,  307,  307,
      307,  307,  307,  326,  327,  303,  307,  303,  303,  307,

      303,  303,    0,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303
    } ;

static yyconst short int yy_nxt[815] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   27,   27,
       27,   27,   27,   27,   28,   29,   30,   31,   32,   33,
       33,   33,   34,   35,   10,   36,   37,   33,   38,   39,
       40,   33,   41,   42,   33,   33,   43,   33,   44,   45,
       33,   33,   46,   47,   48,   49,   50,   33,   51,   33,
       33,   52,   53,   54,   56,   56,   59,   59,   63,   60,
       60,   63,   67,   71,   72,   93,   79,   64,   74,   93,
       64,   88,   89,   75,   91,   92,   93,   93,   79,  154,
      302,   57,   57,   68,  155,   76,   79,   93,   93,   61,

       61,   77,  184,   78,   78,   78,   78,   78,   78,   78,
       78,   93,   93,  301,  117,   93,   79,   80,   79,   79,
       93,  131,   93,  118,   81,   79,   82,   79,   79,   80,
       83,   79,   79,   84,   79,   79,   79,   79,   85,   79,
       79,   79,   79,   79,   79,   79,   86,   79,   98,   93,
       95,  122,   93,   93,  123,   93,  132,   93,   93,   93,
       99,   79,  100,   96,  101,  104,   93,  105,  107,   93,
      102,  108,  103,   79,  112,   93,  106,  113,   93,  135,
       93,   79,   93,   93,  119,   93,   93,  109,  136,  144,
       93,  133,  178,   93,  124,  167,  167,  120,  114,  110,

      111,  145,  121,  127,  115,  116,  137,  125,  126,  175,
      128,   93,   93,  129,  174,  180,  167,  130,   93,  146,
       93,  177,  138,  176,   93,  139,   93,  140,  141,  181,
      179,  142,   93,   93,   93,  147,  234,  183,  148,  182,
      149,  150,  190,  185,  151,  158,  158,  158,  158,  158,
      158,  158,  158,  170,  170,  170,  170,  170,  170,  170,
       93,  187,   93,  186,  191,   93,   93,   93,  192,  197,
       93,  208,  159,  161,  170,  161,  193,  188,  162,  162,
      162,  162,  162,  162,  162,  162,   77,  189,  163,  163,
      163,  163,  163,  163,  163,  163,   93,   93,   93,  154,

       93,   93,  164,   93,  155,  198,   93,  167,  167,  163,
       93,  200,  196,   93,  164,  165,  203,  199,  166,  171,
      171,  171,  171,  171,  171,  171,  171,  256,  167,  256,
       93,   93,  171,  171,  194,  204,  201,  220,  228,   93,
      171,  171,  171,  171,  171,  171,  171,  206,  207,  226,
      195,  202,  209,  205,   93,  227,  210,  212,  212,  212,
      212,  212,  212,  212,  214,  214,  214,  214,  214,  214,
      214,  216,  218,  218,  218,  218,  218,  218,  218,  218,
      229,   93,   93,  216,  159,  219,  219,  219,  219,  219,
      219,  219,  219,   93,  225,   93,   93,   93,   93,   93,

       93,   93,   93,   93,   93,   93,  219,   93,   93,   93,
       93,   93,  165,   93,  216,   93,   93,   93,   93,   93,
       93,   93,   93,   93,   93,   93,  216,  159,   93,   93,
       93,   93,  230,  231,  232,  233,  235,  239,  240,   93,
      237,   93,  242,  249,  236,   93,  245,  238,  246,  247,
      248,   93,   93,   93,  241,  243,  274,  244,  251,  250,
      265,  267,  264,  268,  270,  271,   93,   93,  291,  266,
      269,  272,  273,   93,  276,   93,   93,  288,  275,  277,
      278,  257,  257,   93,  279,  257,  257,  257,  257,  257,
      257,  257,  257,  287,   93,  296,  159,   93,  289,   93,

      290,   93,   93,   93,   93,   93,  293,   93,   93,  286,
      285,  284,  283,  260,  300,  159,   93,   93,  292,   93,
       93,   93,   93,   93,   93,   93,  297,   55,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   58,   58,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   58,   58,   58,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   94,
       93,   93,  263,  262,   94,   94,   94,   94,  261,   94,
       94,  134,  134,  134,  134,  260,  134,  134,  134,  134,
      134,  134,  258,  134,  134,  143,   93,  143,   93,  143,

      143,  143,  143,  143,  143,  143,   93,  143,  143,  152,
       93,  152,  152,  152,   93,  152,  152,  152,  152,  152,
      152,  152,  152,  153,  153,  153,  153,  153,  153,  153,
      153,  153,  153,  153,  153,  153,  153,  157,   93,  157,
      157,  157,  157,  157,  157,  157,  157,  157,  157,  157,
      157,  160,  160,  160,  160,   93,  160,  160,  215,   93,
      215,   93,   93,  215,  215,  252,  252,  252,   93,  224,
      223,  252,  253,  253,  253,  253,  222,  221,  253,  254,
      254,  254,  169,  168,  217,  254,  255,  255,  255,  255,
      303,  213,  255,  259,  211,   93,   93,   93,  259,  259,

      280,  280,  280,   93,   93,  173,  280,  281,  281,  281,
      172,  169,  168,  281,  282,  156,   97,   93,   90,  282,
      282,  294,  294,  294,   87,   73,   70,  294,  295,  295,
      295,   69,   66,   65,  295,  298,  298,  298,  303,  303,
      303,  298,  299,  299,  299,  303,  303,  303,  299,    9,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303
    } ;

static yyconst short int yy_chk[815] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,    7,    5,
        6,    8,   16,   23,   23,   44,   27,    7,   25,   51,
        8,   30,   30,   25,   32,   32,  300,  107,   27,   64,
      299,    3,    4,   16,   64,   25,   27,   38,   46,    5,

        6,   26,  107,   26,   26,   26,   26,   26,   26,   26,
       26,   34,   39,  298,   44,   47,   26,   26,   26,   26,
       41,   51,   40,   44,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   26,   26,   38,   45,
       34,   46,   42,   49,   47,   48,   53,  101,   43,   96,
       39,   78,   39,   34,   40,   41,   50,   41,   42,   95,
       40,   42,   40,   78,   43,   99,   41,   43,  104,   57,
      103,   78,  100,  102,   45,  106,  105,   42,   57,   61,
      182,   53,  101,  115,   48,   82,   82,   45,   43,   42,

       42,   61,   45,   49,   43,   43,   57,   48,   48,   96,
       49,  111,  117,   50,   95,  103,   82,   50,  109,   61,
      118,  100,   57,   99,  119,   57,  108,   57,   57,  104,
      102,   57,  130,  122,  293,   61,  182,  106,   61,  105,
       61,   61,  115,  108,   61,   77,   77,   77,   77,   77,
       77,   77,   77,   85,   85,   85,   85,   85,   85,   85,
      121,  111,  112,  109,  117,  123,  124,  126,  118,  122,
      113,  130,   77,   80,   85,   80,  119,  112,   80,   80,
       80,   80,   80,   80,   80,   80,   81,  113,   81,   81,
       81,   81,   81,   81,   81,   81,  120,  129,  128,  154,

      127,  125,   81,  177,  154,  123,  175,  167,  167,   81,
      176,  124,  121,  131,   81,   81,  126,  123,   81,   86,
       86,   86,   86,   86,   86,   86,   86,  216,  167,  216,
      178,  292,   86,   86,  120,  127,  125,  167,  177,  291,
       86,   86,   86,   86,   86,   86,   86,  128,  129,  175,
      120,  125,  131,  127,  174,  176,  131,  142,  142,  142,
      142,  142,  142,  142,  151,  151,  151,  151,  151,  151,
      151,  158,  161,  161,  161,  161,  161,  161,  161,  161,
      178,  179,  180,  158,  158,  162,  162,  162,  162,  162,
      162,  162,  162,  186,  174,  190,  181,  183,  192,  195,

      193,  199,  200,  201,  202,  204,  162,  203,  207,  209,
      205,  206,  162,  210,  215,  226,  228,  230,  231,  244,
      235,  241,  246,  239,  232,  236,  215,  215,  245,  243,
      267,  273,  179,  179,  180,  181,  183,  193,  195,  249,
      190,  250,  200,  207,  186,  251,  203,  192,  204,  205,
      206,  269,  264,  272,  199,  201,  244,  202,  210,  209,
      228,  231,  226,  232,  236,  239,  274,  277,  273,  230,
      235,  241,  243,  288,  246,  297,  290,  267,  245,  249,
      250,  319,  319,  289,  251,  256,  256,  256,  256,  256,
      256,  256,  256,  264,  287,  283,  282,  279,  269,  278,

      272,  276,  275,  271,  270,  268,  277,  266,  265,  263,
      262,  261,  260,  259,  297,  257,  248,  247,  274,  242,
      240,  238,  237,  234,  233,  229,  288,  304,  304,  304,
      304,  304,  304,  304,  304,  304,  304,  304,  304,  304,
      304,  305,  305,  305,  305,  305,  305,  305,  305,  305,
      305,  305,  305,  305,  305,  306,  306,  306,  306,  306,
      306,  306,  306,  306,  306,  306,  306,  306,  306,  307,
      227,  225,  224,  223,  307,  307,  307,  307,  220,  307,
      307,  308,  308,  308,  308,  218,  308,  308,  308,  308,
      308,  308,  217,  308,  308,  309,  208,  309,  198,  309,

      309,  309,  309,  309,  309,  309,  197,  309,  309,  310,
      196,  310,  310,  310,  194,  310,  310,  310,  310,  310,
      310,  310,  310,  311,  311,  311,  311,  311,  311,  311,
      311,  311,  311,  311,  311,  311,  311,  312,  191,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  313,  313,  313,  313,  189,  313,  313,  314,  188,
      314,  187,  185,  314,  314,  315,  315,  315,  184,  171,
      170,  315,  316,  316,  316,  316,  169,  168,  316,  317,
      317,  317,  166,  165,  159,  317,  318,  318,  318,  318,
      153,  150,  318,  320,  141,  116,  114,  110,  320,  320,

      321,  321,  321,   98,   94,   92,  321,  322,  322,  322,
       88,   84,   83,  322,  323,   73,   37,   33,   31,  323,
      323,  324,  324,  324,   28,   24,   21,  324,  325,  325,
      325,   20,   15,   13,  325,  326,  326,  326,    9,    0,
        0,  326,  327,  327,  327,    0,    0,    0,  327,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,

      303,  303,  303,  303,  303,  303,  303,  303,  303,  303,
      303,  303,  303,  303
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "compiler/lex.l"
#define INITIAL 0
#define YY_NEVER_INTERACTIVE 1
#define CHAR 1

#define STRING 2

#define ML_COMMENT 3

#line 11 "compiler/lex.l"
	#include <stdio.h>
    #include <stdlib.h>
    #include <string.h>
    #include <ctype.h>

    char str[1024];
    int lineNumber = 1;
#line 666 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 20 "compiler/lex.l"



    void removeUnderline();
    void removeType(char *typeName);
	void convertCharacterCodeToString(char characterCode[], int startPosition, char *string);


#line 822 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 304 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 750 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 28 "compiler/lex.l"
{ lineNumber++; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "compiler/lex.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "compiler/lex.l"
{ printf("Found KW_AS: %s\n", yytext); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "compiler/lex.l"
{ printf("Found KW_BREAK: %s\n", yytext); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "compiler/lex.l"
{ printf("Found KW_CONST: %s\n", yytext); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "compiler/lex.l"
{ printf("Found KW_CONTINUE: %s\n", yytext); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "compiler/lex.l"
{ printf("Found KW_CRATE: %s\n", yytext); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "compiler/lex.l"
{ printf("Found KW_ELSE: %s\n", yytext); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "compiler/lex.l"
{ printf("Found KW_ENUM: %s\n", yytext); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "compiler/lex.l"
{ printf("Found KW_EXTERN: %s\n", yytext); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "compiler/lex.l"
{ printf("Found KW_FALSE: %s\n", yytext); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "compiler/lex.l"
{ printf("Found KW_FN: %s\n", yytext); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "compiler/lex.l"
{ printf("Found KW_FOR: %s\n", yytext); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "compiler/lex.l"
{ printf("Found KW_IF: %s\n", yytext); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "compiler/lex.l"
{ printf("Found KW_IMPL: %s\n", yytext); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "compiler/lex.l"
{ printf("Found KW_IN: %s\n", yytext); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "compiler/lex.l"
{ printf("Found KW_LET: %s\n", yytext); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "compiler/lex.l"
{ printf("Found KW_LOOP: %s\n", yytext); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "compiler/lex.l"
{ printf("Found KW_MATCH: %s\n", yytext); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "compiler/lex.l"
{ printf("Found KW_MOD: %s\n", yytext); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "compiler/lex.l"
{ printf("Found KW_MOVE: %s\n", yytext); }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "compiler/lex.l"
{ printf("Found KW_MUT: %s\n", yytext); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "compiler/lex.l"
{ printf("Found KW_PUB: %s\n", yytext); }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "compiler/lex.l"
{ printf("Found KW_REF: %s\n", yytext); }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "compiler/lex.l"
{ printf("Found KW_RETURN: %s\n", yytext); }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "compiler/lex.l"
{ printf("Found KW_SELFVALUE: %s\n", yytext); }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "compiler/lex.l"
{ printf("Found KW_SELFTYPE: %s\n", yytext); }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "compiler/lex.l"
{ printf("Found KW_STATIC: %s\n", yytext); }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "compiler/lex.l"
{ printf("Found KW_STRUCT: %s\n", yytext); }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "compiler/lex.l"
{ printf("Found KW_SUPER: %s\n", yytext); }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "compiler/lex.l"
{ printf("Found KW_TRAIT: %s\n", yytext); }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "compiler/lex.l"
{ printf("Found KW_TRUE: %s\n", yytext); }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "compiler/lex.l"
{ printf("Found KW_TYPE: %s\n", yytext); }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "compiler/lex.l"
{ printf("Found KW_UNSAFE: %s\n", yytext); }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "compiler/lex.l"
{ printf("Found KW_USE: %s\n", yytext); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 64 "compiler/lex.l"
{ printf("Found KW_WHERE: %s\n", yytext); }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 65 "compiler/lex.l"
{ printf("Found KW_WHILE: %s\n", yytext); }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 68 "compiler/lex.l"
{ printf("Found TYPE_BOOL: %s\n", yytext); }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 69 "compiler/lex.l"
{ printf("Found TYPE_I32: %s\n", yytext); }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 70 "compiler/lex.l"
{ printf("Found TYPE_I64: %s\n", yytext); }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 71 "compiler/lex.l"
{ printf("Found TYPE_F32: %s\n", yytext); }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 72 "compiler/lex.l"
{ printf("Found TYPE_F64: %s\n", yytext); }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 73 "compiler/lex.l"
{ printf("Found TYPE_STRING: %s\n", yytext); }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 74 "compiler/lex.l"
{ printf("Found TYPE_CHAR: %s\n", yytext); }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 77 "compiler/lex.l"
{ printf("Found OPERATOR_PLUS: %s\n", yytext); }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 78 "compiler/lex.l"
{ printf("Found OPERATOR_MINUS: %s\n", yytext); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 79 "compiler/lex.l"
{ printf("Found OPERATOR_MUL: %s\n", yytext); }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 80 "compiler/lex.l"
{ printf("Found OPERATOR_DIV: %s\n", yytext); }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 81 "compiler/lex.l"
{ printf("Found OPERATOR_MOD: %s\n", yytext); }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 83 "compiler/lex.l"
{ printf("Found OPERATOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 84 "compiler/lex.l"
{ printf("Found OPERATOR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 85 "compiler/lex.l"
{ printf("Found OPERATOR_NOT_EQUAL: %s\n", yytext); }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 86 "compiler/lex.l"
{ printf("Found OPERATOR_LESS: %s\n", yytext); }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 87 "compiler/lex.l"
{ printf("Found OPERATOR_MORE: %s\n", yytext); }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 88 "compiler/lex.l"
{ printf("Found OPERATOR_LESS_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 89 "compiler/lex.l"
{ printf("Found OPERATOR_MORE_OR_EQUAL: %s\n", yytext); }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "compiler/lex.l"
{ printf("Found OPERATOR_AMPERSAND: %s\n", yytext); }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_OR: %s\n", yytext); }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_NOT: %s\n", yytext); }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_XOR: %s\n", yytext); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT: %s\n", yytext); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "compiler/lex.l"
{ printf("Found OPERATOR_AND: %s\n", yytext); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "compiler/lex.l"
{ printf("Found OPERATOR_OR: %s\n", yytext); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 101 "compiler/lex.l"
{ printf("Found OPERATOR_PLUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 102 "compiler/lex.l"
{ printf("Found OPERATOR_MINUS_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 103 "compiler/lex.l"
{ printf("Found OPERATOR_MUL_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 104 "compiler/lex.l"
{ printf("Found OPERATOR_DIV_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 105 "compiler/lex.l"
{ printf("Found OPERATOR_MOD_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 106 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_AND_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 107 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_OR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 108 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_XOR_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 109 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_LEFT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 110 "compiler/lex.l"
{ printf("Found OPERATOR_BIT_RIGHT_SHIFT_ASSIGNMENT: %s\n", yytext); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 112 "compiler/lex.l"
{ printf("Found OPERATOR_POINT: %s\n", yytext); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 113 "compiler/lex.l"
{ printf("Found OPERATOR_RANGE: %s\n", yytext); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 114 "compiler/lex.l"
{ printf("Found OPERATOR_RANGE_ASSIGMENT: %s\n", yytext); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "compiler/lex.l"
{ printf("Found OPERATOR_ARROW: %s\n", yytext); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 117 "compiler/lex.l"
{ printf("Found LEFT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 118 "compiler/lex.l"
{ printf("Found RIGHT_ROUND_BRACKET: %s\n", yytext); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 119 "compiler/lex.l"
{ printf("Found LEFT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 120 "compiler/lex.l"
{ printf("Found RIGHT_SQUARE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 121 "compiler/lex.l"
{ printf("Found LEFT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 122 "compiler/lex.l"
{ printf("Found RIGHT_FIGURE_BRACKET: %s\n", yytext); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 124 "compiler/lex.l"
{ printf("Found COMMA: %s\n", yytext); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 125 "compiler/lex.l"
{ printf("Found SEMICOLON: %s\n", yytext); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 126 "compiler/lex.l"
{ printf("Found COLON: %s\n", yytext); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 127 "compiler/lex.l"
{ printf("Found TWO_COLON: %s\n", yytext); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 130 "compiler/lex.l"
{ strcpy(str,""); BEGIN(ML_COMMENT); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 131 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 132 "compiler/lex.l"
{ lineNumber++; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 133 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 134 "compiler/lex.l"
{ printf("Found ML_COMMENT: %s\n", str);  BEGIN(INITIAL); }
	YY_BREAK
case YY_STATE_EOF(ML_COMMENT):
#line 135 "compiler/lex.l"
{ printf("ML_COMMENT Error in line %d: comments are not closed\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 137 "compiler/lex.l"
{ printf("Found COMMENT: %s\n", yytext); }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 139 "compiler/lex.l"
{ strcpy(str,""); BEGIN(STRING); }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 140 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 141 "compiler/lex.l"
{ lineNumber++; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 142 "compiler/lex.l"
{ strcat(str,"\n"); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 143 "compiler/lex.l"
{ strcat(str,"\r"); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 144 "compiler/lex.l"
{ strcat(str,"\t"); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 145 "compiler/lex.l"
{ strcat(str,"\0"); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 146 "compiler/lex.l"
{ strcat(str,"\\"); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 147 "compiler/lex.l"
{ strcat(str,"\""); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 148 "compiler/lex.l"
{
    int x = strtol(yytext + 3,NULL, 16); 
    if(x <= 127)
    {
        char tmp[2];
        tmp[0] = x;
        tmp[1] = 0;
        strcat(str, tmp);
    }
    else
    {
     printf("CHAR Error in line %d: Unicode are not supported\n", lineNumber); 
    }
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 162 "compiler/lex.l"
{
    char string[2];
    convertCharacterCodeToString(yytext, 2, string);
    strcat(str, string);
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 167 "compiler/lex.l"
{ printf("Found STRING: %s\n", str); BEGIN(INITIAL);}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 168 "compiler/lex.l"
{ printf("STRING Error in line %d: there is no closing quotation mark\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 169 "compiler/lex.l"
{ printf("STRING Error in line %d: slash\n", lineNumber); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 172 "compiler/lex.l"
{ strcpy(str,""); BEGIN(CHAR); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 173 "compiler/lex.l"
{ strcat(str,yytext); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 174 "compiler/lex.l"
{ strcat(str,"\n"); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 175 "compiler/lex.l"
{ strcat(str,"\r"); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 176 "compiler/lex.l"
{ strcat(str,"\t"); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 177 "compiler/lex.l"
{ strcat(str,"\0"); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 178 "compiler/lex.l"
{ strcat(str,"\\"); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 179 "compiler/lex.l"
{ strcat(str,"\'"); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 180 "compiler/lex.l"
{
    int x = strtol(yytext + 3,NULL, 16); 
    if(x <= 127)
    {
        char tmp[2];
        tmp[0] = x;
        tmp[1] = 0;
        strcat(str, tmp);
    }
    else
    {
     printf("CHAR Error in line %d: Unicode are not supported\n", lineNumber); 
    }
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 194 "compiler/lex.l"
{
    char string[2];
    convertCharacterCodeToString(yytext, 2, string);
    strcat(str, string);
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 199 "compiler/lex.l"
{
    if(strlen(str) == 1) {
        printf("Found CHAR:  %c\n", str[0]);
    }
    else if(strlen(str) == 0)
    {
        printf("CHAR Error in line %d: empty char literal\n", lineNumber);
    }
    else {
        printf("CHAR Error in line %d: more than one char in quote\n", lineNumber);
    }
    BEGIN(INITIAL);
}
	YY_BREAK
case YY_STATE_EOF(CHAR):
#line 212 "compiler/lex.l"
{ printf("CHAR Error in line %d: there is no closing quotation mark\n", lineNumber); BEGIN(INITIAL);}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 213 "compiler/lex.l"
{ printf("CHAR Error in line %d: slash\n", lineNumber); }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 216 "compiler/lex.l"
{

    removeType("i32");
    removeUnderline();
    printf("Found DECIMAL_NUMBER: %d\n", atoi(str));
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 223 "compiler/lex.l"
{

    removeType("i32");
    removeUnderline();
    if(strlen(str) > 2)
    {
         printf("Found BIN_NUMBER: %d\n", strtol(str + 2, NULL, 2));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 237 "compiler/lex.l"
{

    removeType("i32");
    removeUnderline();
    if(strlen(str) > 2)
    {
         printf("Found OCTAL_NUMBER: %d\n", strtol(str + 2, NULL, 8));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 251 "compiler/lex.l"
{

    removeType("i32");
    removeUnderline();
    if(strlen(str) > 2)
    {
         printf("Found HEXADECIMAL_NUMBER: %d\n", strtol(str + 2, NULL, 16));
    }
    else
    {
        printf("NUMBER Error in line %d: incorrect format\n", lineNumber);
    }
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 265 "compiler/lex.l"
{
    removeType("f64");
    removeUnderline();
    printf("Found DOUBLE: %lf\n", atof(str), str);
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 271 "compiler/lex.l"
{
    removeType("f64");
    removeUnderline();
    printf("Found DOUBLE: %lf\n", atof(str));
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 277 "compiler/lex.l"
{ printf("Found IDENTIFIER: %s\n", yytext);}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 278 "compiler/lex.l"
{ printf("Found MACROS: %s\n", yytext);}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 279 "compiler/lex.l"
{ printf("Error in line %d: incorrect IDENTIFIER\n", lineNumber); }
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 281 "compiler/lex.l"
ECHO;
	YY_BREAK
#line 1657 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 304 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 304 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 303);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 281 "compiler/lex.l"


void convertCharacterCodeToString(char characterCode[], int startPosition, char *string)
{
    string[0] = strtol(characterCode + startPosition,NULL, 16);
    string[1] = '\0';
}

void removeUnderline()
{
  int pos = 0;
  for(int i = 0; i < strlen(yytext); i++)
  {
        if(yytext[i] != '_')
        {
            str[pos++] = yytext[i];
        }
  }

  str[pos] = '\0';
  strcpy(yytext, str);
}

void removeType(char *typeName)
{
    strcpy(str, yytext);
    char* p = strstr(str, typeName);
    if(p != NULL)
    {
        int pos = strlen(str)  - strlen(typeName);
        str[pos] = 0;
    }
}

int main(int argc, char** argv) {

    if (argc != 2) {
        printf("Filename is not found");
        return 1;
    }

    const char *filename= argv[1];
    
    FILE *file = fopen(filename, "r");
    if (file == NULL) {
        printf("File opening error");
        return 1;
    }

    yyin = file;
    yylex();
    fclose(file);

    return 0;
}


